-- CP-05 operational seed: 60 coherent completed events for local/VPS testing and ML retraining.
-- Safe to re-run.
-- Business refs generated by this patch: TRAIN-001 through TRAIN-060.

BEGIN;

INSERT INTO core.clients (client_id, name, priority, industry, contact_person_name, notes)
SELECT
    ('81000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    'Training Client ' || lpad(i::text, 3, '0'),
    (ARRAY['low','medium','high','critical'])[1 + (i % 4)]::core.priority_level,
    (ARRAY['technology','retail','finance','media'])[1 + (i % 4)],
    'Training Contact ' || lpad(i::text, 3, '0'),
    'Business training record TRAIN-' || lpad(i::text, 3, '0')
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (client_id) DO UPDATE
SET name = EXCLUDED.name,
    priority = EXCLUDED.priority,
    industry = EXCLUDED.industry,
    contact_person_name = EXCLUDED.contact_person_name,
    notes = EXCLUDED.notes;

INSERT INTO core.locations (
    location_id, name, city, address_line, country_code, location_type,
    parking_difficulty, access_difficulty, setup_complexity_score, notes
)
SELECT
    ('82000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    'Training Venue ' || lpad(i::text, 3, '0'),
    (ARRAY['Warsaw','Gdansk','Krakow','Poznan','Wroclaw'])[1 + (i % 5)],
    'Training Street ' || i,
    'PL',
    (ARRAY['conference_center','indoor','stadium','outdoor','office'])[1 + (i % 5)]::core.location_type,
    1 + (i % 5),
    1 + ((i + 1) % 5),
    1 + (i % 10),
    'Business training venue TRAIN-' || lpad(i::text, 3, '0')
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (location_id) DO UPDATE
SET name = EXCLUDED.name,
    city = EXCLUDED.city,
    address_line = EXCLUDED.address_line,
    country_code = EXCLUDED.country_code,
    location_type = EXCLUDED.location_type,
    parking_difficulty = EXCLUDED.parking_difficulty,
    access_difficulty = EXCLUDED.access_difficulty,
    setup_complexity_score = EXCLUDED.setup_complexity_score,
    notes = EXCLUDED.notes;

INSERT INTO core.equipment_types (equipment_type_id, type_name, category, description, default_setup_minutes, default_teardown_minutes)
VALUES
    ('83000000-0000-0000-0000-000000000001', 'Training Audio Kit', 'audio', 'Audio kit used in TRAIN cases', 45, 30),
    ('83000000-0000-0000-0000-000000000002', 'Training LED Screen', 'video', 'LED screen kit used in TRAIN cases', 60, 45)
ON CONFLICT (equipment_type_id) DO UPDATE
SET type_name = EXCLUDED.type_name,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    default_setup_minutes = EXCLUDED.default_setup_minutes,
    default_teardown_minutes = EXCLUDED.default_teardown_minutes;

INSERT INTO core.events (
    event_id, client_id, location_id, event_name, event_type, event_subtype,
    description, attendee_count, planned_start, planned_end, priority, status,
    budget_estimate, currency_code, source_channel, requires_transport, requires_setup,
    requires_teardown, notes, created_by
)
SELECT
    ('80000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('81000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('82000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    'TRAIN-' || lpad(i::text, 3, '0') || ' ' || (ARRAY['Executive Summit','Product Launch','Retail Roadshow','Music Night','Investor Day'])[1 + (i % 5)],
    (ARRAY['conference','brand_activation','concert','corporate_meeting'])[1 + (i % 4)],
    (ARRAY['corporate','outdoor_launch','live_music','roadshow'])[1 + (i % 4)],
    'Coherent completed training case TRAIN-' || lpad(i::text, 3, '0'),
    80 + (i * 8),
    ('2025-09-01 08:00:00+00'::timestamptz + (i || ' days')::interval),
    ('2025-09-01 08:00:00+00'::timestamptz + (i || ' days')::interval + ((4 + (i % 6)) || ' hours')::interval),
    (ARRAY['low','medium','high','critical'])[1 + (i % 4)]::core.priority_level,
    'completed'::core.event_status,
    (18000 + (i * 1250))::numeric(12,2),
    'PLN',
    'training_seed_cp05',
    (i % 2 = 0),
    true,
    (i % 3 <> 0),
    'Business ID TRAIN-' || lpad(i::text, 3, '0') || '; deterministic UUID suffix ' || lpad(i::text, 12, '0'),
    'cp05_seed'
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (event_id) DO UPDATE
SET event_name = EXCLUDED.event_name,
    description = EXCLUDED.description,
    attendee_count = EXCLUDED.attendee_count,
    planned_start = EXCLUDED.planned_start,
    planned_end = EXCLUDED.planned_end,
    priority = EXCLUDED.priority,
    status = EXCLUDED.status,
    budget_estimate = EXCLUDED.budget_estimate,
    source_channel = EXCLUDED.source_channel,
    notes = EXCLUDED.notes;

INSERT INTO core.event_requirements (requirement_id, event_id, requirement_type, role_required, quantity, mandatory, notes)
SELECT
    ('84000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('80000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    'person_role'::core.requirement_type,
    'coordinator'::core.person_role,
    (1 + (i % 3))::numeric,
    true,
    'TRAIN-' || lpad(i::text, 3, '0') || ' coordinator requirement'
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (requirement_id) DO UPDATE
SET quantity = EXCLUDED.quantity,
    notes = EXCLUDED.notes;

INSERT INTO core.event_requirements (requirement_id, event_id, requirement_type, equipment_type_id, quantity, mandatory, notes)
SELECT
    ('85000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('80000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    'equipment_type'::core.requirement_type,
    CASE WHEN i % 2 = 0 THEN '83000000-0000-0000-0000-000000000001'::uuid ELSE '83000000-0000-0000-0000-000000000002'::uuid END,
    (1 + (i % 2))::numeric,
    true,
    'TRAIN-' || lpad(i::text, 3, '0') || ' equipment requirement'
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (requirement_id) DO UPDATE
SET equipment_type_id = EXCLUDED.equipment_type_id,
    quantity = EXCLUDED.quantity,
    notes = EXCLUDED.notes;

INSERT INTO ops.event_outcomes (
    event_id, finished_on_time, total_delay_minutes, actual_cost, overtime_cost,
    transport_cost, sla_breached, client_satisfaction_score, internal_quality_score,
    margin_estimate, summary_notes, closed_at
)
SELECT
    ('80000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    (i % 5 <> 0),
    CASE WHEN i % 5 = 0 THEN 20 + (i % 35) ELSE 0 END,
    (17000 + (i * 1180) + CASE WHEN i % 5 = 0 THEN 3500 ELSE 0 END)::numeric(12,2),
    CASE WHEN i % 4 = 0 THEN (450 + i * 12)::numeric(12,2) ELSE NULL END,
    CASE WHEN i % 2 = 0 THEN (900 + i * 20)::numeric(12,2) ELSE NULL END,
    (i % 13 = 0),
    (3.4 + ((i % 7) * 0.2))::numeric(3,2),
    (3.5 + ((i % 6) * 0.2))::numeric(3,2),
    (4000 + i * 180)::numeric(12,2),
    'Completed coherent training case TRAIN-' || lpad(i::text, 3, '0'),
    ('2025-09-01 08:00:00+00'::timestamptz + (i || ' days')::interval + ((4 + (i % 6)) || ' hours')::interval + (CASE WHEN i % 5 = 0 THEN '35 minutes' ELSE '0 minutes' END)::interval)
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (event_id) DO UPDATE
SET finished_on_time = EXCLUDED.finished_on_time,
    total_delay_minutes = EXCLUDED.total_delay_minutes,
    actual_cost = EXCLUDED.actual_cost,
    overtime_cost = EXCLUDED.overtime_cost,
    transport_cost = EXCLUDED.transport_cost,
    sla_breached = EXCLUDED.sla_breached,
    client_satisfaction_score = EXCLUDED.client_satisfaction_score,
    internal_quality_score = EXCLUDED.internal_quality_score,
    margin_estimate = EXCLUDED.margin_estimate,
    summary_notes = EXCLUDED.summary_notes,
    closed_at = EXCLUDED.closed_at;

INSERT INTO ops.actual_timings (
    timing_id, event_id, phase_name, planned_start, actual_start, planned_end,
    actual_end, notes
)
SELECT
    ('86000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('80000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    'event_runtime'::ops.phase_name,
    ('2025-09-01 08:00:00+00'::timestamptz + (i || ' days')::interval),
    ('2025-09-01 08:00:00+00'::timestamptz + (i || ' days')::interval),
    ('2025-09-01 08:00:00+00'::timestamptz + (i || ' days')::interval + ((4 + (i % 6)) || ' hours')::interval),
    ('2025-09-01 08:00:00+00'::timestamptz + (i || ' days')::interval + ((4 + (i % 6)) || ' hours')::interval + (CASE WHEN i % 5 = 0 THEN '35 minutes' ELSE '0 minutes' END)::interval),
    'TRAIN-' || lpad(i::text, 3, '0') || ' actual timing'
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (timing_id) DO UPDATE
SET actual_end = EXCLUDED.actual_end,
    notes = EXCLUDED.notes;

COMMIT;
