-- CP-06 operational company seed.
-- Safe to re-run. It keeps existing database state and upserts operational data.
-- Business refs generated by this patch: OP-001 through OP-060.

BEGIN;

WITH admin_user AS (
    SELECT user_id FROM auth.users WHERE username = 'admin' ORDER BY created_at LIMIT 1
)
UPDATE core.clients c
SET
    name = 'Client ' || lpad(split_part(c.client_id::text, '-', 5)::bigint::text, 3, '0'),
    priority = (ARRAY['medium','high','critical','low'])[1 + (split_part(c.client_id::text, '-', 5)::bigint % 4)]::core.priority_level,
    industry = (ARRAY['technology','retail','finance','media'])[1 + (split_part(c.client_id::text, '-', 5)::bigint % 4)],
    contact_person_name = (ARRAY['Anna Nowak','Marek Zielinski','Julia Adams','Piotr Kowal'])[1 + (split_part(c.client_id::text, '-', 5)::bigint % 4)],
    notes = 'Operational client profile for recurring business events.'
WHERE c.client_id::text LIKE '81000000-0000-0000-0000-%';

UPDATE core.locations l
SET
    name = (ARRAY['Amber Expo','National Stadium','ICE Krakow','Poznan Congress Center','Wroclaw Business Hall'])[1 + (split_part(l.location_id::text, '-', 5)::bigint % 5)] || ' ' || lpad(split_part(l.location_id::text, '-', 5)::bigint::text, 3, '0'),
    city = (ARRAY['Warsaw','Gdansk','Krakow','Poznan','Wroclaw'])[1 + (split_part(l.location_id::text, '-', 5)::bigint % 5)],
    address_line = 'Business Avenue ' || split_part(l.location_id::text, '-', 5)::bigint,
    postal_code = lpad((10000 + split_part(l.location_id::text, '-', 5)::bigint)::text, 5, '0'),
    country_code = 'PL',
    location_type = (ARRAY['conference_center','indoor','stadium','outdoor','office'])[1 + (split_part(l.location_id::text, '-', 5)::bigint % 5)]::core.location_type,
    latitude = (52.00 + (split_part(l.location_id::text, '-', 5)::bigint % 10) * 0.07)::numeric(9,6),
    longitude = (20.00 + (split_part(l.location_id::text, '-', 5)::bigint % 10) * 0.09)::numeric(9,6),
    parking_difficulty = 1 + (split_part(l.location_id::text, '-', 5)::bigint % 5),
    access_difficulty = 1 + ((split_part(l.location_id::text, '-', 5)::bigint + 1) % 5),
    setup_complexity_score = 2 + (split_part(l.location_id::text, '-', 5)::bigint % 7),
    notes = 'Fully profiled operational venue with access, parking and setup data.'
WHERE l.location_id::text LIKE '82000000-0000-0000-0000-%';

INSERT INTO core.skills (skill_id, skill_name, skill_category, description)
VALUES
    ('86500000-0000-0000-0000-000000000001', 'Audio engineering', 'technical', 'Live audio setup, tuning and incident recovery.'),
    ('86500000-0000-0000-0000-000000000002', 'Lighting design', 'technical', 'Stage and architectural lighting setup.'),
    ('86500000-0000-0000-0000-000000000003', 'Video wall operation', 'technical', 'LED wall, projection and signal routing.'),
    ('86500000-0000-0000-0000-000000000004', 'Stage management', 'operations', 'Run-of-show coordination and backstage control.'),
    ('86500000-0000-0000-0000-000000000005', 'Client coordination', 'operations', 'Client communication and onsite escalation.'),
    ('86500000-0000-0000-0000-000000000006', 'Transport logistics', 'logistics', 'Vehicle dispatch and load planning.'),
    ('86500000-0000-0000-0000-000000000007', 'Warehouse handling', 'logistics', 'Picking, packing and equipment returns.'),
    ('86500000-0000-0000-0000-000000000008', 'Project leadership', 'management', 'Budget, risk and stakeholder management.')
ON CONFLICT (skill_id) DO UPDATE
SET skill_name = EXCLUDED.skill_name,
    skill_category = EXCLUDED.skill_category,
    description = EXCLUDED.description;

INSERT INTO core.equipment_types (equipment_type_id, type_name, category, description, default_setup_minutes, default_teardown_minutes)
VALUES
    ('83000000-0000-0000-0000-000000000001', 'Line Array Audio Kit', 'audio', 'Main PA set for medium and large venues.', 70, 45),
    ('83000000-0000-0000-0000-000000000002', 'LED Screen 4x3m', 'video', 'Modular LED screen wall for stages and conferences.', 80, 55),
    ('83000000-0000-0000-0000-000000000003', 'Wireless Microphone Set', 'audio', 'Eight-channel wireless microphone rack.', 25, 20),
    ('83000000-0000-0000-0000-000000000004', 'Stage Lighting Package', 'lighting', 'Moving heads, wash fixtures and control desk.', 65, 45),
    ('83000000-0000-0000-0000-000000000005', 'Streaming Encoder Kit', 'video', 'Encoder, capture devices and network failover.', 35, 25),
    ('83000000-0000-0000-0000-000000000006', 'Portable Stage Deck', 'stage', 'Modular stage deck with stairs and skirts.', 90, 70),
    ('83000000-0000-0000-0000-000000000007', 'Power Distribution Rack', 'power', 'Power distribution, cabling and protection.', 45, 35),
    ('83000000-0000-0000-0000-000000000008', 'Registration Kiosk Set', 'frontdesk', 'Tablets, printers and attendee check-in stands.', 30, 25)
ON CONFLICT (equipment_type_id) DO UPDATE
SET type_name = EXCLUDED.type_name,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    default_setup_minutes = EXCLUDED.default_setup_minutes,
    default_teardown_minutes = EXCLUDED.default_teardown_minutes;

INSERT INTO core.resources_people (
    person_id, full_name, role, employment_type, home_base_location_id,
    availability_status, max_daily_hours, max_weekly_hours, cost_per_hour,
    reliability_notes, active
)
SELECT
    ('87000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    (ARRAY['Anna','Marek','Julia','Piotr','Katarzyna','Tomasz','Ewa','Michal'])[1 + (i % 8)] || ' ' ||
    (ARRAY['Nowak','Zielinski','Adams','Kowal','Wisniewska','Lewandowski'])[1 + (i % 6)] || ' ' || lpad(i::text, 2, '0'),
    (ARRAY['technician_audio','technician_light','technician_video','stage_manager','coordinator','driver','warehouse_operator','project_manager'])[1 + (i % 8)]::core.person_role,
    (ARRAY['employee','contractor','freelancer','agency_staff'])[1 + (i % 4)]::core.employment_type,
    ('82000000-0000-0000-0000-' || lpad(((i % 20) + 1)::text, 12, '0'))::uuid,
    'available'::core.resource_status,
    (8 + (i % 3))::numeric(4,2),
    (40 + (i % 4) * 4)::numeric(5,2),
    (95 + i * 4)::numeric(10,2),
    'Reliable operational team member. Business ref PER-' || lpad(i::text, 3, '0'),
    true
FROM generate_series(1, 48) AS s(i)
ON CONFLICT (person_id) DO UPDATE
SET full_name = EXCLUDED.full_name,
    role = EXCLUDED.role,
    employment_type = EXCLUDED.employment_type,
    home_base_location_id = EXCLUDED.home_base_location_id,
    availability_status = EXCLUDED.availability_status,
    max_daily_hours = EXCLUDED.max_daily_hours,
    max_weekly_hours = EXCLUDED.max_weekly_hours,
    cost_per_hour = EXCLUDED.cost_per_hour,
    reliability_notes = EXCLUDED.reliability_notes,
    active = EXCLUDED.active,
    updated_at = NOW();

INSERT INTO core.people_skills (person_id, skill_id, skill_level, certified, last_verified_at, notes)
SELECT
    ('87000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('86500000-0000-0000-0000-' || lpad((1 + (i % 8))::text, 12, '0'))::uuid,
    3 + (i % 3),
    (i % 2 = 0),
    '2026-01-15 10:00:00+00'::timestamptz + (i || ' days')::interval,
    'Verified operational skill mapping.'
FROM generate_series(1, 48) AS s(i)
ON CONFLICT (person_id, skill_id) DO UPDATE
SET skill_level = EXCLUDED.skill_level,
    certified = EXCLUDED.certified,
    last_verified_at = EXCLUDED.last_verified_at,
    notes = EXCLUDED.notes;

INSERT INTO core.equipment (
    equipment_id, equipment_type_id, asset_tag, serial_number, status,
    warehouse_location_id, transport_requirements, replacement_available,
    hourly_cost_estimate, purchase_date, notes, active
)
SELECT
    ('88000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('83000000-0000-0000-0000-' || lpad((1 + (i % 8))::text, 12, '0'))::uuid,
    'EQ-' || lpad(i::text, 4, '0'),
    'SN-CP06-' || lpad(i::text, 5, '0'),
    'available'::core.resource_status,
    ('82000000-0000-0000-0000-' || lpad(((i % 20) + 1)::text, 12, '0'))::uuid,
    (ARRAY['single van case','two-person lift','flight case','requires power check'])[1 + (i % 4)],
    (i % 3 <> 0),
    (45 + i * 3)::numeric(10,2),
    ('2023-01-01'::date + (i || ' days')::interval)::date,
    'Operational asset with business ref EQ-' || lpad(i::text, 4, '0'),
    true
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (equipment_id) DO UPDATE
SET equipment_type_id = EXCLUDED.equipment_type_id,
    asset_tag = EXCLUDED.asset_tag,
    serial_number = EXCLUDED.serial_number,
    status = EXCLUDED.status,
    warehouse_location_id = EXCLUDED.warehouse_location_id,
    transport_requirements = EXCLUDED.transport_requirements,
    replacement_available = EXCLUDED.replacement_available,
    hourly_cost_estimate = EXCLUDED.hourly_cost_estimate,
    purchase_date = EXCLUDED.purchase_date,
    notes = EXCLUDED.notes,
    active = EXCLUDED.active,
    updated_at = NOW();

INSERT INTO core.vehicles (
    vehicle_id, vehicle_name, vehicle_type, registration_number, capacity_notes,
    status, home_location_id, cost_per_km, cost_per_hour, active
)
SELECT
    ('89000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    (ARRAY['City Van','Cargo Truck','Crew Car','Stage Trailer'])[1 + (i % 4)] || ' ' || lpad(i::text, 2, '0'),
    (ARRAY['van','truck','car','trailer'])[1 + (i % 4)]::core.vehicle_type,
    'WX' || lpad(i::text, 4, '0') || 'CP',
    (ARRAY['audio cases and crew','large stage cargo','four-person crew transfer','stage deck trailer'])[1 + (i % 4)],
    'available'::core.resource_status,
    ('82000000-0000-0000-0000-' || lpad(((i % 20) + 1)::text, 12, '0'))::uuid,
    (2.40 + i * 0.08)::numeric(10,2),
    (70 + i * 3)::numeric(10,2),
    true
FROM generate_series(1, 16) AS s(i)
ON CONFLICT (vehicle_id) DO UPDATE
SET vehicle_name = EXCLUDED.vehicle_name,
    vehicle_type = EXCLUDED.vehicle_type,
    registration_number = EXCLUDED.registration_number,
    capacity_notes = EXCLUDED.capacity_notes,
    status = EXCLUDED.status,
    home_location_id = EXCLUDED.home_location_id,
    cost_per_km = EXCLUDED.cost_per_km,
    cost_per_hour = EXCLUDED.cost_per_hour,
    active = EXCLUDED.active,
    updated_at = NOW();

INSERT INTO core.people_availability (availability_id, person_id, available_from, available_to, is_available, source, notes)
SELECT
    ('87100000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('87000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    '2026-01-01 00:00:00+00'::timestamptz,
    '2027-12-31 23:59:00+00'::timestamptz,
    true,
    'cp06_operational_seed',
    'Default operational availability window.'
FROM generate_series(1, 48) AS s(i)
ON CONFLICT (availability_id) DO UPDATE
SET available_from = EXCLUDED.available_from,
    available_to = EXCLUDED.available_to,
    is_available = EXCLUDED.is_available,
    source = EXCLUDED.source,
    notes = EXCLUDED.notes;

INSERT INTO core.equipment_availability (availability_id, equipment_id, available_from, available_to, is_available, source, notes)
SELECT
    ('88100000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('88000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    '2026-01-01 00:00:00+00'::timestamptz,
    '2027-12-31 23:59:00+00'::timestamptz,
    true,
    'cp06_operational_seed',
    'Default operational equipment availability.'
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (availability_id) DO UPDATE
SET available_from = EXCLUDED.available_from,
    available_to = EXCLUDED.available_to,
    is_available = EXCLUDED.is_available,
    source = EXCLUDED.source,
    notes = EXCLUDED.notes;

INSERT INTO core.vehicle_availability (availability_id, vehicle_id, available_from, available_to, is_available, source, notes)
SELECT
    ('89100000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('89000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    '2026-01-01 00:00:00+00'::timestamptz,
    '2027-12-31 23:59:00+00'::timestamptz,
    true,
    'cp06_operational_seed',
    'Default operational vehicle availability.'
FROM generate_series(1, 16) AS s(i)
ON CONFLICT (availability_id) DO UPDATE
SET available_from = EXCLUDED.available_from,
    available_to = EXCLUDED.available_to,
    is_available = EXCLUDED.is_available,
    source = EXCLUDED.source,
    notes = EXCLUDED.notes;

WITH admin_user AS (
    SELECT user_id FROM auth.users WHERE username = 'admin' ORDER BY created_at LIMIT 1
)
UPDATE core.events e
SET
    event_name = 'OP-' || lpad(split_part(e.event_id::text, '-', 5)::bigint::text, 3, '0') || ' ' || (ARRAY['Executive Summit','Product Launch','Retail Roadshow','Music Night','Investor Day'])[1 + (split_part(e.event_id::text, '-', 5)::bigint % 5)],
    event_type = (ARRAY['conference','brand_activation','concert','corporate_meeting'])[1 + (split_part(e.event_id::text, '-', 5)::bigint % 4)],
    event_subtype = (ARRAY['executive','product','retail','live','investor'])[1 + (split_part(e.event_id::text, '-', 5)::bigint % 5)],
    description = 'Operational business event based on realistic historical planning patterns. Business ref OP-' || lpad(split_part(e.event_id::text, '-', 5)::bigint::text, 3, '0'),
    attendee_count = 80 + (split_part(e.event_id::text, '-', 5)::bigint * 8),
    budget_estimate = (18000 + (split_part(e.event_id::text, '-', 5)::bigint * 1250))::numeric(12,2),
    currency_code = 'PLN',
    source_channel = 'operational_seed_cp06',
    requires_transport = (split_part(e.event_id::text, '-', 5)::bigint % 2 = 0),
    requires_setup = true,
    requires_teardown = (split_part(e.event_id::text, '-', 5)::bigint % 3 <> 0),
    planned_start = CASE
        WHEN split_part(e.event_id::text, '-', 5)::bigint <= 20
            THEN ('2026-02-01 09:00:00+00'::timestamptz + ((split_part(e.event_id::text, '-', 5)::bigint - 1) * interval '2 days'))
        ELSE ('2026-05-10 09:00:00+00'::timestamptz + ((split_part(e.event_id::text, '-', 5)::bigint - 21) * interval '3 days'))
    END,
    planned_end = CASE
        WHEN split_part(e.event_id::text, '-', 5)::bigint <= 20
            THEN ('2026-02-01 17:00:00+00'::timestamptz + ((split_part(e.event_id::text, '-', 5)::bigint - 1) * interval '2 days'))
        ELSE ('2026-05-10 17:00:00+00'::timestamptz + ((split_part(e.event_id::text, '-', 5)::bigint - 21) * interval '3 days'))
    END,
    status = CASE
        WHEN split_part(e.event_id::text, '-', 5)::bigint <= 20 THEN 'completed'::core.event_status
        ELSE 'planned'::core.event_status
    END,
    priority = (ARRAY['low','medium','high','critical'])[1 + (split_part(e.event_id::text, '-', 5)::bigint % 4)]::core.priority_level,
    notes = 'Business ID OP-' || lpad(split_part(e.event_id::text, '-', 5)::bigint::text, 3, '0') || '; seeded from realistic operational templates.',
    created_by = 'cp06_operational_seed',
    created_by_user_id = COALESCE((SELECT user_id FROM admin_user), e.created_by_user_id)
WHERE e.event_id::text LIKE '80000000-0000-0000-0000-%';

UPDATE core.event_requirements r
SET
    role_required = (ARRAY['coordinator','technician_audio','technician_light','stage_manager'])[1 + (split_part(r.requirement_id::text, '-', 5)::bigint % 4)]::core.person_role,
    quantity = (1 + (split_part(r.requirement_id::text, '-', 5)::bigint % 3))::numeric,
    notes = 'Operational person requirement for OP-' || lpad(split_part(r.event_id::text, '-', 5)::bigint::text, 3, '0')
WHERE r.requirement_id::text LIKE '84000000-0000-0000-0000-%';

UPDATE core.event_requirements r
SET
    equipment_type_id = ('83000000-0000-0000-0000-' || lpad((1 + (split_part(r.requirement_id::text, '-', 5)::bigint % 8))::text, 12, '0'))::uuid,
    quantity = (1 + (split_part(r.requirement_id::text, '-', 5)::bigint % 2))::numeric,
    notes = 'Operational equipment requirement for OP-' || lpad(split_part(r.event_id::text, '-', 5)::bigint::text, 3, '0')
WHERE r.requirement_id::text LIKE '85000000-0000-0000-0000-%';

INSERT INTO core.event_requirements (requirement_id, event_id, requirement_type, vehicle_type_required, quantity, mandatory, notes)
SELECT
    ('85500000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    ('80000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
    'vehicle_type'::core.requirement_type,
    (ARRAY['van','truck','car','trailer'])[1 + (i % 4)]::core.vehicle_type,
    1::numeric,
    true,
    'Operational vehicle requirement for OP-' || lpad(i::text, 3, '0')
FROM generate_series(1, 60) AS s(i)
ON CONFLICT (requirement_id) DO UPDATE
SET vehicle_type_required = EXCLUDED.vehicle_type_required,
    quantity = EXCLUDED.quantity,
    notes = EXCLUDED.notes;

UPDATE ops.event_outcomes o
SET
    summary_notes = 'Completed operational event OP-' || lpad(split_part(o.event_id::text, '-', 5)::bigint::text, 3, '0') || ' with validated cost, timing and satisfaction metrics.'
WHERE o.event_id::text LIKE '80000000-0000-0000-0000-%'
  AND split_part(o.event_id::text, '-', 5)::bigint <= 20;

DELETE FROM ops.event_outcomes o
WHERE o.event_id::text LIKE '80000000-0000-0000-0000-%'
  AND split_part(o.event_id::text, '-', 5)::bigint > 20;

UPDATE ops.actual_timings t
SET
    actual_start = COALESCE(actual_start, planned_start),
    notes = 'Operational actual timing for OP-' || lpad(split_part(t.event_id::text, '-', 5)::bigint::text, 3, '0')
WHERE t.event_id::text LIKE '80000000-0000-0000-0000-%'
  AND split_part(t.event_id::text, '-', 5)::bigint <= 20;

DELETE FROM ops.actual_timings t
WHERE t.event_id::text LIKE '80000000-0000-0000-0000-%'
  AND split_part(t.event_id::text, '-', 5)::bigint > 20;

COMMIT;
